### ISSUE TITLE
Does multiple view inputs or Stable diffusion-2-1 improves the result?

### ISSUE THREAD

**Issue by YJ-142150** [zhizdev/sparsefusion#3]
Hi, thanks for your great work!
I'm really interested in VLDM and I have some questions about it.
Does 4~6 inputs produce better results than 2 inputs?
Did you also tried weights of stable-diffusion-v2-1?

**Comment by zhizdev** [comment]
Hi, thanks for asking these questions! 

1) Giving 4~6 inputs to VLDM does produce better results than 2 inputs; however, with more inputs, feature reprojection methods, PixelNeRF and EFT, start to perform pretty well as well. 

2) We have not tried using stable-diffusion weights for the UNet since the architecture is incompatible.

**Comment by YJ-142150** [comment]
Then did you extracted only vae weights in stable diffusion v1-3 weights?

**Comment by YJ-142150** [comment]
Well, I missed README.md. Thank you for answering!
